### ISSUE TITLE
 Implement UserDetail Component

### ISSUE THREAD

**Issue by chakrapaul** [Slowlorises/p5#4]
The UserDetail component is responsible for fetching and displaying the details of a specific user based on the provided userId. This component plays a crucial role in providing users with relevant information about individual users within the application.

Task:

- Implement the UserDetail component to fetch user details based on the userId provided in the URL params (this.props.match.params.userId).

- Ensure proper error handling for scenarios where the user details cannot be fetched or are unavailable.

- Design and implement a user-friendly UI to render the user details in a pleasing way, considering factors such as readability, aesthetics, and accessibility.

- Include a navigation link within the component to allow users to navigate to the user's photos page (/photos/:userId).

- Test the component thoroughly to ensure functionality, performance, and cross-browser compatibility.

- Implement loading indicators to provide feedback to users while user details are being fetched.

- Optimize the component's performance by minimizing unnecessary re-renders and optimizing data fetching.

- Ensure that the component follows best practices for React development, including proper state management and component lifecycle methods.

**Comment by RithwikaNarla** [comment]
I have successfully finished all tasks that are given above.
